#mystr="Harry is a good boy"
#print(mystr)
#print(mystr[7])
#print(mystr[0:4])
#print(mystr[0:5])
#print(len(mystr))
#print(mystr[0:18])
#print(mystr[0:19])
#print(mystr[0:78])
#print(mystr[::5559])
#print(mystr[::-2])
#print(mystr.endswith("bdoy"))
#print(mystr.count("o"))
#print(mystr.capitalize())
#print(mystr.find("is"))
#print(mystr.upper())
#print(mystr.replace("is","are"))
mystr="Ansh is from Uttar Pradesh"
print(mystr.replace("from ","from "))

